# Generated by Django 3.2 on 2024-06-21 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=40)),
                ('bookPublisher', models.CharField(max_length=40)),
                ('bookAuthor', models.CharField(max_length=40)),
                ('bookIntroduction', models.TextField()),
                ('bookPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('TypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=40)),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('borrowId', models.IntegerField(primary_key=True, serialize=False)),
                ('hasReturned', models.BooleanField(default=False)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staffinfo')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookNum', models.IntegerField()),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booktype'),
        ),
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addNum', models.IntegerField()),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staffinfo')),
            ],
        ),
    ]
